#include <juce_gui_basics/juce_gui_basics.h>
#include "dsp/AudioEngine.h"
#include "ui/MainComponent.h"
#include "ui/MenuBarIcon.h"

// If JuceHeader.h is generated by CMake, we should include it
#if __has_include("JuceHeader.h")
 #include "JuceHeader.h"
#endif

class EquinoxApplication : public juce::JUCEApplication
{
public:
    EquinoxApplication() {}

    const juce::String getApplicationName() override       { return "Equinox"; }
    const juce::String getApplicationVersion() override    { return "0.1.0"; }
    bool moreThanOneInstanceAllowed() override             { return false; }

    void initialise(const juce::String& commandLine) override
    {
        // Named lock to prevent multiple instances
        m_instanceLock = std::make_unique<juce::InterProcessLock>("com.equinox.app.lock");
        if (!m_instanceLock->enter(100))
        {
            // Already running, quit this instance
            juce::Logger::writeToLog("Equinox: Another instance is already running. Exiting.");
            quit();
            return;
        }

        // Initialize persistent logging in a known location
        juce::File logFile = juce::File::getCurrentWorkingDirectory().getChildFile("log.txt");
        
        m_logger = std::make_unique<juce::FileLogger>(logFile, "Equinox Launch Log");
        juce::Logger::setCurrentLogger(m_logger.get());
        
        juce::Logger::writeToLog("--- Equinox v0.1.0 Starting ---");
        juce::Logger::writeToLog("Log path: " + logFile.getFullPathName());

        // Check for Microphone Permission (Essential for macOS input)
        juce::RuntimePermissions::request(juce::RuntimePermissions::recordAudio, [this](bool granted) {
            juce::Logger::writeToLog(granted ? "Microphone Permission: GRANTED" : "Microphone Permission: DENIED");
            m_audioEngine.initialize();
        });

        m_menuBarIcon = std::make_unique<equinox::MenuBarIcon>(m_audioEngine, [this] {
            showMainWindow();
        });

        showMainWindow();
    }


    void shutdown() override
    {
        m_mainWindow = nullptr;
        m_menuBarIcon = nullptr;
        m_audioEngine.shutdown();
    }

    void systemRequestedQuit() override
    {
        quit();
    }

    void anotherInstanceStarted(const juce::String& commandLine) override 
    {
        showMainWindow();
    }

    void showMainWindow()
    {
        if (m_mainWindow == nullptr)
        {
            m_mainWindow = std::make_unique<MainWindow>(getApplicationName(), m_audioEngine);
        }
        else
        {
            m_mainWindow->setVisible(true);
            m_mainWindow->toFront(true);
        }
    }

    class MainWindow : public juce::DocumentWindow
    {
    public:
        MainWindow(juce::String name, equinox::AudioEngine& engine)
            : DocumentWindow(name,
                             juce::Desktop::getInstance().getDefaultLookAndFeel()
                                                         .findColour(juce::ResizableWindow::backgroundColourId),
                             DocumentWindow::allButtons)
        {
            setUsingNativeTitleBar(true);
            setContentOwned(new equinox::MainComponent(engine), true);
            setResizable(true, true);
            
            // Set window as a utility window and stay on top
            setAlwaysOnTop(true);
            
            centreWithSize(getWidth(), getHeight());
            setVisible(true);
        }

        void closeButtonPressed() override
        {
            // Just hide the window, don't quit the app
            setVisible(false);
        }

    private:
        JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(MainWindow)
    };

private:
    equinox::AudioEngine m_audioEngine;
    std::unique_ptr<juce::InterProcessLock> m_instanceLock;
    std::unique_ptr<juce::FileLogger> m_logger;
    std::unique_ptr<equinox::MenuBarIcon> m_menuBarIcon;
    std::unique_ptr<MainWindow> m_mainWindow;
};

START_JUCE_APPLICATION(EquinoxApplication)
