#include <juce_gui_basics/juce_gui_basics.h>
#include "dsp/AudioEngine.h"
#include "ui/MainComponent.h"
#include "ui/MenuBarIcon.h"

// If JuceHeader.h is generated by CMake, we should include it
#if __has_include("JuceHeader.h")
 #include "JuceHeader.h"
#endif

class EquinoxApplication : public juce::JUCEApplication
{
public:
    EquinoxApplication() {}

    const juce::String getApplicationName() override       { return "Equinox"; }
    const juce::String getApplicationVersion() override    { return "0.1.0"; }
    bool moreThanOneInstanceAllowed() override             { return true; }

    void initialise(const juce::String& commandLine) override
    {
        m_audioEngine.initialize();

        m_menuBarIcon = std::make_unique<equinox::MenuBarIcon>(m_audioEngine, [this] {
            showMainWindow();
        });

        showMainWindow();
    }


    void shutdown() override
    {
        m_mainWindow = nullptr;
        m_menuBarIcon = nullptr;
        m_audioEngine.shutdown();
    }

    void systemRequestedQuit() override
    {
        quit();
    }

    void anotherInstanceStarted(const juce::String& commandLine) override {}

    void showMainWindow()
    {
        if (m_mainWindow == nullptr)
        {
            m_mainWindow = std::make_unique<MainWindow>(getApplicationName(), m_audioEngine);
        }
        else
        {
            m_mainWindow->setVisible(true);
            m_mainWindow->toFront(true);
        }
    }

    class MainWindow : public juce::DocumentWindow
    {
    public:
        MainWindow(juce::String name, equinox::AudioEngine& engine)
            : DocumentWindow(name,
                             juce::Desktop::getInstance().getDefaultLookAndFeel()
                                                         .findColour(juce::ResizableWindow::backgroundColourId),
                             DocumentWindow::allButtons)
        {
            setUsingNativeTitleBar(true);
            setContentOwned(new equinox::MainComponent(engine), true);
            setResizable(true, true);
            
            // Set window as a utility window and stay on top
            setAlwaysOnTop(true);
            
            centreWithSize(getWidth(), getHeight());
            setVisible(true);
        }

        void closeButtonPressed() override
        {
            // Just hide the window, don't quit the app
            setVisible(false);
        }

    private:
        JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR(MainWindow)
    };

private:
    equinox::AudioEngine m_audioEngine;
    std::unique_ptr<equinox::MenuBarIcon> m_menuBarIcon;
    std::unique_ptr<MainWindow> m_mainWindow;
};

START_JUCE_APPLICATION(EquinoxApplication)
